#!/usr/bin/env python3
"""Hold every production source file under the line limit, or to the size it already is.

A file grows one reasonable edit at a time, and no single edit is the one that
made it too large to read. So the limit is a ratchet rather than a target: a file
already over it is recorded in `.rulesync/file-size-baseline.json` with its
current count, may shrink, and may not grow; a file not recorded may not cross
it at all.

  python3 scripts/check-file-size.py            Fail on a new or grown oversized file
  python3 scripts/check-file-size.py --check    The same, spelled out for CI
  python3 scripts/check-file-size.py --update   Lower recorded counts to what the files are now

`--update` only ever lowers: it drops a file that fell under the limit or was
removed, and tightens one that shrank. It refuses while any file is new or
grown, because writing that down would be raising the ceiling, not recording it.
`--check` fails on a loose entry too, so the baseline stays exact and the slack a
shrink earns cannot be spent by the next edit.

Production source is code under plugins/ and scripts/. The copies under
`plugins/<plugin>/skills/<skill>/shared/` are generated by sync-shared.py, so
the plugin-level `shared/` they come from is the file held here.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASELINE = Path(".rulesync") / "file-size-baseline.json"
PRODUCTION_ROOTS = ("plugins", "scripts")
SOURCE_SUFFIXES = {".py", ".sh", ".js", ".mjs", ".cjs", ".ts", ".css", ".html"}
SKIPPED_DIRECTORIES = {"__pycache__", ".git", "node_modules"}


def is_vendored_copy(relative: Path) -> bool:
    """True for `plugins/<plugin>/skills/<skill>/shared/...`, which sync-shared.py writes."""

    parts = relative.parts
    return len(parts) > 5 and parts[0] == "plugins" and parts[2] == "skills" and parts[4] == "shared"


def production_files(root: Path) -> dict[str, int]:
    """Return {relative path: line count} for every production source file under root."""

    counts: dict[str, int] = {}
    for top in PRODUCTION_ROOTS:
        for path in sorted((root / top).rglob("*")):
            relative = path.relative_to(root)
            if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
                continue
            if SKIPPED_DIRECTORIES.intersection(relative.parts) or is_vendored_copy(relative):
                continue
            counts[relative.as_posix()] = len(path.read_text(encoding="utf-8").splitlines())
    return counts


def load_baseline(root: Path) -> tuple[int, dict[str, int]]:
    data = json.loads((root / BASELINE).read_text(encoding="utf-8"))
    return int(data["limit"]), {path: int(count) for path, count in data["files"].items()}


def write_baseline(root: Path, limit: int, files: dict[str, int]) -> None:
    payload = {"limit": limit, "files": dict(sorted(files.items()))}
    (root / BASELINE).write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def violations(limit: int, recorded: dict[str, int], current: dict[str, int]) -> list[str]:
    """Return one line per file that crossed the limit or grew past its recorded count."""

    errors: list[str] = []
    for path, count in sorted(current.items()):
        allowed = recorded.get(path)
        if allowed is None and count > limit:
            errors.append(f"{path}: {count} lines, over the {limit}-line limit. Split it by concept.")
        elif allowed is not None and count > allowed:
            errors.append(f"{path}: grew from {allowed} to {count} lines; a recorded file may only shrink.")
    return errors


def tightened(limit: int, recorded: dict[str, int], current: dict[str, int]) -> dict[str, int]:
    """Return the baseline with every count lowered to the file's size now, never raised."""

    return {
        path: min(allowed, current[path])
        for path, allowed in recorded.items()
        if path in current and current[path] > limit
    }


def stale_entries(recorded: dict[str, int], lowered: dict[str, int]) -> list[str]:
    """Return one line per recorded entry that `--update` would lower or drop."""

    stale: list[str] = []
    for path, allowed in sorted(recorded.items()):
        if path not in lowered:
            stale.append(f"{path}: recorded at {allowed} lines but no longer over the limit or present.")
        elif lowered[path] < allowed:
            stale.append(f"{path}: recorded at {allowed} lines but is {lowered[path]} now.")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on a new, grown, or loosely recorded file")
    mode.add_argument("--update", action="store_true", help="lower recorded counts; never raise or add one")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args()

    root = args.root.resolve()
    limit, recorded = load_baseline(root)
    current = production_files(root)
    errors = violations(limit, recorded, current)
    lowered = tightened(limit, recorded, current)

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    if args.update:
        write_baseline(root, limit, lowered)
        print(f"{BASELINE.as_posix()}: {len(lowered)} files recorded over {limit} lines")
        return 0

    stale = stale_entries(recorded, lowered)
    for line in stale:
        print(f"error: {line} Run `python3 scripts/check-file-size.py --update`.", file=sys.stderr)
    if stale:
        return 1
    print(f"{len(current)} production source files; {len(recorded)} recorded over {limit} lines, none grew")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
